/*
 *	CLASE 12: 
 */

USE NORTHWIND
GO

EXEC SP_HELP [ORDER DETAILS]
SELECT * FROM [Order Details]
GO

EXEC SP_HELP PRODUCTS
SELECT * FROM PRODUCTS
GO

CREATE PROCEDURE CREATE_DETAIL
	@orderID INT,
	@productID INT,
	@quantity SMALLINT,
	@discount REAL
AS
DECLARE @unitPrice MONEY
SELECT @unitPrice = unitprice FROM Products
	WHERE ProductID = @productID
IF  (@orderID IS NULL) OR
	(@productID IS NULL) OR
	(@quantity IS NULL) OR
	(@discount IS NULL)
	BEGIN
		PRINT 'NULL VALUE'
		RETURN 1
	END
IF NOT EXISTS (SELECT ProductID FROM PRODUCTS WHERE ProductID = @productID)
	BEGIN
		PRINT 'THIS PRODUCT DOESNT EXIST'
		RETURN 2
	END
IF NOT EXISTS (SELECT OrderID FROM ORDERS WHERE OrderID = @orderID)
	BEGIN
		PRINT 'THE ORDER DOESNT EXIST'
		RETURN 3
	END
IF (SELECT UnitsInStock FROM PRODUCTS WHERE ProductID = @productID) < @quantity
	BEGIN
		PRINT 'THERE IS NO ENOUGH STOCK FOR THIS PRODUCT'
		RETURN 4
	END
IF (SELECT Discontinued FROM PRODUCTS WHERE ProductID = @productID) = 1
	BEGIN
		PRINT 'THIS PRODUCT IS DISCONTINUED'
		RETURN 5
	END
	BEGIN TRAN
		UPDATE Products
			SET UnitsInStock = UnitsInStock - @quantity
			WHERE ProductID = @productID
		INSERT INTO [Order Details] (OrderID, ProductID, UnitPrice, Quantity, Discount)
		VALUES (@orderID, @productID, @unitPrice, @quantity, @discount)
		IF @@ERROR <> 0
			BEGIN
				ROLLBACK TRAN
				PRINT 'ERROR IN DATABASE'
				RETURN @@ERROR
			END
	COMMIT TRAN
	PRINT 'DETAIL CREATED SUCCESSFULLY'
	RETURN 0
GO

EXEC SP_HELP ORDERS
INSERT INTO ORDERS (CustomerID, EmployeeID)
VALUES ('ALFKI', 1)
GO

SELECT * FROM ORDERS
SELECT * FROM PRODUCTS
GO

-- CASO EXITOSO
DECLARE @code INT
EXEC @code = CREATE_DETAIL 11078, 10, 10, 0
PRINT @code
GO

-- CUANDO EL PEDIDO NO EXISTE
DECLARE @code INT
EXEC @code = CREATE_DETAIL 11087, 1, 1, 0
PRINT @code
GO

-- CUANDO NO HAY STOCK
DECLARE @code INT
EXEC @code = CREATE_DETAIL 11078, 10, 80, 0
PRINT @code
GO

-- CUANDO EL PRODUCTO ESTA DESCONTINUADO
DECLARE @code INT
EXEC @code = CREATE_DETAIL 11078, 9, 10, 0
PRINT @code
GO

