USE EduTec
GO

CREATE TRIGGER TR_INSERT_COURSE
ON CURSO
AFTER INSERT
AS
PRINT 'SE HA EJECUTADO UN TRIGGER'
GO

-- GENERA ERROR PORQUE YA EXISTE
INSERT INTO Curso VALUES ('C001', 'A', 'MICROSOFT WORD')
GO

INSERT INTO CURSO VALUES ('C902', 'A', 'WINDOWS 11 PRO')
GO

DROP TRIGGER TR_INSERT_COURSE
GO

-- CREACION DE TRIGGER 'INSTEAD OF'
CREATE TRIGGER TR_INSERT_COURSE
ON CURSO
INSTEAD OF INSERT
AS
-- HACE ALGUN TIPO DE 'ROLLBACK' 
PRINT 'SE EJECUTO INSTEAD OF INSERT TRIGGER'
GO


-- CREACION DE TRIGGER 'INSTEAD OF'
ALTER TRIGGER TR_INSERT_COURSE
ON CURSO
INSTEAD OF INSERT
AS
-- ARROJARA 'ROWS @@ROWCOUNT AFFECTED' A PESAR DE NO HACERLO
-- UN TRIGGER ABRE UN TRANSACCION
-- TRANSACCION ES UN PROCESO QUE SE ABRE EN RAM
-- POR ESO SALE 'ROW AFFECTED', PERO CUANDO EL TRIGGER REEMPLAZA EL INSERT
-- HACE ALGUN TIPO DE 'ROLLBACK' 
PRINT 'SE EJECUTO INSTEAD OF INSERT TRIGGER'
PRINT 'EL CONTENIDO DE LA TABLA ES: '
SELECT * FROM inserted
GO

INSERT INTO CURSO VALUES ('C913', 'A', 'WINDOWS XP PRO')
GO

SELECT * FROM Curso

-- modificando mas del trigger
ALTER TRIGGER TR_INSERT_COURSE
ON CURSO
INSTEAD OF INSERT
AS
-- ARROJARA 'ROWS @@ROWCOUNT AFFECTED' A PESAR DE NO HACERLO
-- UN TRIGGER ABRE UN TRANSACCION
-- TRANSACCION ES UN PROCESO QUE SE ABRE EN RAM
-- POR ESO SALE 'ROW AFFECTED', PERO CUANDO EL TRIGGER REEMPLAZA EL INSERT
-- HACE ALGUN TIPO DE 'ROLLBACK' 
PRINT 'SE EJECUTO INSTEAD OF INSERT TRIGGER'
PRINT 'EL CONTENIDO DE LA TABLA ES: '
SELECT * FROM inserted
INSERT INTO Curso SELECT * FROM inserted
GO

DROP TRIGGER TR_INSERT_COURSE
GO

CREATE TRIGGER TR_INSERT_COURSE
ON CURSO
AFTER INSERT
AS
PRINT 'SE HA EJECUTADO TRIGGER AFTER'
SELECT * FROM INSERTED
PRINT 'SE CANCELA'
ROLLBACK TRAN
go

INSERT INTO CURSO VALUES ('C002', 'A', 'MICROSFOT ACCESS')
GO

INSERT INTO CURSO VALUES ('C123', 'A', 'VISUAL STUDIO CODE')
GO